language: objective-c
os: osx
osx_image: xcode7.3
sudo: required
rvm:
- 2.1.2

before_install: 
- chmod +x ./Testes/instalador.sh

before_script: 
- chmod +x ./Testes/compilador.sh


install:
- ./Testes/instalador.sh
script:
- travis_wait 30 mvn install
- ./Testes/compilador.sh
