language: objective-c
os: osx
osx_image: xcode7.3
sudo: required
rvm:
- 2.1.2

before_install: 
- chmod +x ./Testes/instalador.sh

before_script: 
- chmod +x ./Testes/testes.sh
- chmod +x ./Testes/upload.sh


install:
- ./Testes/instalador.sh
script:
- travis_wait 50 ./Testes/compilador.sh
- travis_wait 20 ./Testes/upload.sh
