// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class Project_CSV : MonoBehaviour
{

	public TextAsset file;

	void Awake()
	{
		Load(file);
	}

	public class Row
	{
		public string SpriteID;
		public string ClientName;
		public string Difficulty;
		public string Description;
		public string Abstract;
		public string Payment;
		public string Deadline;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = Csv_Parser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.SpriteID = grid [i][0];
			row.ClientName = grid[i][1];
			row.Difficulty = grid[i][2];
			row.Description = grid[i][3];
			row.Abstract = grid[i][4];
			row.Payment = grid[i][5];
			row.Deadline = grid[i][6];
			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_ClientName(string find)
	{
		return rowList.Find(x => x.ClientName == find);
	}
	public List<Row> FindAll_ClientName(string find)
	{
		return rowList.FindAll(x => x.ClientName == find);
	}
	public Row Find_Difficulty(string find)
	{
		return rowList.Find(x => x.Difficulty == find);
	}
	public List<Row> FindAll_Difficulty(string find)
	{
		return rowList.FindAll(x => x.Difficulty == find);
	}
	public Row Find_Description(string find)
	{
		return rowList.Find(x => x.Description == find);
	}
	public List<Row> FindAll_Description(string find)
	{
		return rowList.FindAll(x => x.Description == find);
	}
	public Row Find_Abstract(string find)
	{
		return rowList.Find(x => x.Abstract == find);
	}
	public List<Row> FindAll_Abstract(string find)
	{
		return rowList.FindAll(x => x.Abstract == find);
	}
	public Row Find_Payment(string find)
	{
		return rowList.Find(x => x.Payment == find);
	}
	public List<Row> FindAll_Payment(string find)
	{
		return rowList.FindAll(x => x.Payment == find);
	}
	public Row Find_Deadline(string find)
	{
		return rowList.Find(x => x.Deadline == find);
	}
	public List<Row> FindAll_Deadline(string find)
	{
		return rowList.FindAll(x => x.Deadline == find);
	}

	public Row Find_SpriteId(string find)
	{
		return rowList.Find(x => x.SpriteID == find);
	}
	public List<Row> FindAll_SpriteId(string find)
	{
		return rowList.FindAll(x => x.SpriteID == find);
	}


	public List<string> getInfo(string diff, int id){

		List<string> infos = new List<string> ();

		infos.Add (FindAll_Difficulty (diff) [id].SpriteID);
		infos.Add (FindAll_Difficulty (diff) [id].ClientName);
		infos.Add (FindAll_Difficulty (diff) [id].Description);
		infos.Add (FindAll_Difficulty (diff) [id].Abstract);
		infos.Add (FindAll_Difficulty (diff) [id].Payment);
		infos.Add (FindAll_Difficulty (diff) [id].Deadline);

		return infos;

	}

}